import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Generators for DURF</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>DURF Generators</h1>

        <div className={styles.grid}></div>
        <Link href="/character">Characters</Link>
        {/* <Link href="/monsters">Monsters</Link>
        <Link href="/items">Magical Items</Link> */}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
